using Microsoft.AspNetCore.Mvc;
using ReactWithASP.Server.Domain;
using ReactWithASP.Server.Domain.Abstract;
using ReactWithASP.Server.Infrastructure;

namespace ReactWithASP.Server.Controllers
{
  public class CartResponseDTO
  {
    public Guid? guestID { get; set; }
  }

  public class CartUpdateDTO: CartResponseDTO
  {
    public Int32 ispID { get; set; }
    public Int32 qty { get; set; }
    public IspDTO? isp { get; set; }
  }

  public class IspDTO
  {
    public Int32 id { get; set; }
    public string title { get; set; }
    public string description { get; set; }
    public decimal price { get; set; }
    public Int32 category { get; set; }
  }


  [ApiController]
  [Route("api/[controller]")]
  public class CartController: ControllerBase
  {
    private ICartLineRepository cartLineRepo;
    private IGuestRepository guestRepo;
    private IInStockRepository inStockRepo;

    public CartController(ICartLineRepository rRepo, IGuestRepository gRepo, IInStockRepository pRepo) {
      cartLineRepo = rRepo;
      guestRepo = gRepo;
      inStockRepo = pRepo;
    }

    [HttpGet] // GET api/cart
    public ActionResult Get(){
      IEnumerable<CartLine> cartLines = cartLineRepo.CartLines;
      IEnumerable<CartUpdateDTO> items = cartLines.Select(cartLine => new CartUpdateDTO{
        ispID = (Int32)cartLine.ID,
        qty = (Int32)cartLine.Quantity,
        isp = new IspDTO{
          id          = (Int32)cartLine.ID,
          title       = cartLine.InStockProduct.Title,
          description = cartLine.InStockProduct.Description,
          price       = cartLine.InStockProduct.Price,
          category    = (Int32)cartLine.InStockProduct.Category
        }
      }).ToList();
      return Ok( items ); // Respond with 200 OK, and list of cartLine objects.
    }

    private Guest EnsureGuestIdFromCookie()
    {
      // See if guest id cookie exists...
      Guest guest = null;
      Nullable<Guid> guestId;
      bool createGuest = false;
      string cookieGuestId = Request.Cookies[MyExtensions.GuestCookieName];
      if (string.IsNullOrEmpty(cookieGuestId))
      {
        // Cookie value is not available
        createGuest = true;
        guestId = Guid.NewGuid(); // Create guest ID for the first time.
      }
      else
      {
        // Cookie value is available...
        guestId = cookieGuestId.ToNullableGuid();
        guest = guestRepo.Guests.FirstOrDefault(g => g.ID == guestId); // Look up guest in database.
        if (guest == null){
          createGuest = true; // Record was not found in database.
        }
      }
      
      if (createGuest)
      {
        // Create guest record in database.
        guest = new Guest { ID = guestId };
        guestRepo.SaveGuest(guest);
      }

      // Store guest id in cookie...
      HttpContext.Response.Cookies.Delete(MyExtensions.GuestCookieName);
      Response.Cookies.Append(MyExtensions.GuestCookieName, guestId.ToString(), MyExtensions.GuestCookieOptions);
      return guest;
    }

    [HttpPost]
    [Route("clear")] // POST api/cart/clear
    public ActionResult Clear(Nullable<Guid> guestId)
    {
      // Try to look up the guest. If no guest, create new guest.
      Guest guest = EnsureGuestIdFromCookie();
      guestId = guest.ID;

      // Remove all CartLine records for this Guest ID.
      cartLineRepo.ClearCartLines(guestId);

      // Send back response to client indicating success or failure.
      CartResponseDTO cartResponse = new CartResponseDTO { guestID = guestId };
      return Ok(cartResponse); // 200 ok
    }

    [HttpPost]
    [Route("update")] // POST api/cart/update  Accepts POST data with JSON in Request Body. Content-Type must be 'application/json'
    public ActionResult Update([FromBody] CartUpdateDTO cartUpdate, Nullable<Guid> guestId)
    {
      // Client cart has been updated with the given quantities.
      // Update the user's cart in the database...

      // Try to look up the guest. If no guest, create new guest.
      Guest guest = EnsureGuestIdFromCookie();
      guestId = guest.ID;

      // Look up (isp) product in database.
      InStockProduct isp = inStockRepo.InStockProducts.FirstOrDefault(record => record.ID == cartUpdate.ispID);

      // Create database entry for new CartLine, connected to user/guest and the existing InStockProduct.
      CartLine cartLine = new CartLine{
        AppUser = null,
        Guest = guest,
        GuestID = guestId,
        // ID is generated by database
        InStockProduct = isp,
        InStockProductID = cartUpdate.ispID,
        // PriceTotal is calculated, not mapped
        Quantity = cartUpdate.qty,
        UserID = null
      };
      cartLineRepo.SaveCartLine(cartLine);

      // Prepare JSON for client
      cartUpdate.guestID = guestId;
      cartUpdate.isp = new IspDTO
      {
         id = cartUpdate.ispID,
         title = cartLine.InStockProduct.Title,
         description = cartLine.InStockProduct.Description,
         price = cartLine.InStockProduct.Price,
         category = (Int32)cartLine.InStockProduct.Category
      };

      // Send back response to client indicating success or failure.
      return Ok(cartUpdate); // Respond with 200 OK, and the finalised cart state.
    }
  }
}
