// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactWithASP.Server.Infrastructure;

#nullable disable

namespace ReactWithASP.Server.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250613153047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactWithASP.Server.Domain.InStockProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("InStockProducts");
                });

            modelBuilder.Entity("ReactWithASP.Server.Domain.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ReactWithASP.Server.Domain.OrderedProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("InStockProductID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InStockProductID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderedProducts");
                });

            modelBuilder.Entity("ReactWithASP.Server.Domain.OrderedProduct", b =>
                {
                    b.HasOne("ReactWithASP.Server.Domain.InStockProduct", "InStockProduct")
                        .WithMany()
                        .HasForeignKey("InStockProductID");

                    b.HasOne("ReactWithASP.Server.Domain.Order", "Order")
                        .WithMany("OrderedProducts")
                        .HasForeignKey("OrderID");

                    b.Navigation("InStockProduct");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ReactWithASP.Server.Domain.Order", b =>
                {
                    b.Navigation("OrderedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
